version: '3.4'

services:
  app:
    image: stono/ghost:latest
    build: ./
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ./data/data:/var/www/ghost/current/content/data
      - ./data/images:/var/www/ghost/current/content/images
    ports:
      - 2368:2368
